# -*- coding: utf-8 -*-
"""Criando uma API com Flask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uD_Rg5n6WyVU4mUjiPl8HVzo9ZU6KI9
"""

# Instala as bibliotecas Flask e pyngrok
!pip install flask
!pip install pyngrok

# Adiciona o token de autenticação do ngrok
!ngrok config add-authtoken 'SEU_TOKEN_DE_AUTENTICAÇÃO_NGROK'

# Importa as bibliotecas necessárias
import pandas as pd # Biblioteca para manipulação e análise de dados
from flask import request, jsonify, Flask # Flask para criar aplicações web
from pyngrok import ngrok # Ngrok para criar túneis seguros para localhost

# Cria uma instância da aplicação Flask
app = Flask(__name__)

# Desabilita a formatação bonita das respostas JSON
app.config['JSONIFY_PRETTYPRINT_REGULAR'] = False

# Define a porta para a aplicação Flask
port = "5000"

# Abre um túnel ngrok para a porta especificada
public_url = ngrok.connect(port).public_url
print(f" * ngrok tunnel \"{public_url}")

# Atualiza as URLs base na aplicação Flask para usar o URL público do ngrok
app.config["BASE_URL"] = public_url

# Dados de exemplo que serão servidos pela aplicação Flask

dados = [
    {
        "Number": 1,
        "Name": "Sophie",
        "Age": 28,
        "City": "Madrid",
        "Country": "Espanha"
    },

    {
        "Number": 2,
        "Name": "Miguel",
        "Age": 25,
        "City": "Lisboa",
        "Country": "Portugal"
    },

    {
        "Number": 3,
        "Name": "Aiden",
        "Age": 19,
        "City": "Toronto",
        "Country": "Canadá"
    },

    {
        "Number": 4,
        "Name": "Isabella",
        "Age": 33,
        "City": "Sydney",
        "Country": "Austrália"
    },

    {
        "Number": 5,
        "Name": "Maxime",
        "Age": 27,
        "City": "Bruxelas",
        "Country": "Bélgica"
    }
]

# Define a rota para a página inicial
@app.route("/")

# Retorna os dados de exemplo como uma resposta JSON
def home():
  return jsonify(dados) #mostra dados em json

# Imprime o URL público do túnel ngrok
print(f" * ngrok tunnel \"{public_url}")

# Executa a aplicação Flask
app.run()

# Encerra a aplicação
import sys
sys.exit